server:
  port: 8081

spring:
  application:
    name: flowforge-auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

flowforge:
  jwt:
    secret: ${JWT_SECRET:FlowForgeSuperSecretKeyForJwtSigningMustBeAtLeast256BitsLong!}
    access-token-expiration-ms: 86400000 # 24 hours
    refresh-token-expiration-ms: 604800000 # 7 days
