import type { Node, Edge } from '@xyflow/react';
import type { WorkflowNodeData } from '../types/workflow';

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category?: string;
  tags?: string[];
  nodes: Node<WorkflowNodeData>[];
  edges: Edge[];
}

export const DEMO_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'base-demo-workflow',
    name: 'Payment Webhook VIP Routing',
    description: 'High-value transaction triage from Base Architecture Document: Webhook -> Transform -> HTTP Verification -> IF Amount > 10,000 -> Slack VIP / Email',
    category: 'Finance & Payments',
    tags: ['Webhook', 'Kahn DAG', 'Slack', 'High Volume'],
    nodes: [
      {
        id: 'node-webhook-1',
        type: 'triggerNode',
        position: { x: 50, y: 220 },
        data: {
          label: 'Payment Webhook',
          name: 'Stripe Webhook',
          type: 'TRIGGER_WEBHOOK',
          category: 'TRIGGER',
          description: 'Listens for payment_intent.succeeded events',
          status: 'READY',
          config: {
            webhookPath: '/webhooks/v1/stripe-payments',
          },
          lastOutput: {
            event: 'payment_intent.succeeded',
            amount: 15400,
            currency: 'USD',
            customer: {
              id: 'cus_894218',
              email: 'enterprise@apexcorp.com',
              tier: 'ENTERPRISE',
            },
            orderId: 'ORD-2026-90412',
          },
        },
      },
      {
        id: 'node-transform-2',
        type: 'dataNode',
        position: { x: 380, y: 220 },
        data: {
          label: 'Transform Payload',
          name: 'Normalize Order',
          type: 'DATA_TRANSFORM',
          category: 'DATA',
          description: 'Reshapes raw payload and calculates VIP tier',
          status: 'PENDING',
          config: {
            transformCode: 'return {\n  orderId: $json.orderId,\n  amount: $json.amount,\n  email: $json.customer.email,\n  isHighValue: $json.amount >= 10000\n};',
          },
          lastOutput: {
            orderId: 'ORD-2026-90412',
            amount: 15400,
            email: 'enterprise@apexcorp.com',
            isHighValue: true,
          },
        },
      },
      {
        id: 'node-http-3',
        type: 'actionNode',
        position: { x: 720, y: 220 },
        data: {
          label: 'HTTP Request',
          name: 'Verify Account Risk',
          type: 'ACTION_HTTP',
          category: 'ACTION',
          description: 'Checks fraud risk score with internal service',
          status: 'PENDING',
          config: {
            method: 'POST',
            url: 'https://api.internal-fraud.net/v1/score',
            headers: {
              'Content-Type': 'application/json',
              'X-Risk-Model': 'v4-prod',
            },
            body: '{\n  "email": "{{ $json.email }}",\n  "amount": {{ $json.amount }}\n}',
          },
          lastOutput: {
            riskScore: 0.04,
            status: 'VERIFIED',
            latencyMs: 38,
          },
        },
      },
      {
        id: 'node-if-4',
        type: 'logicNode',
        position: { x: 1060, y: 210 },
        data: {
          label: 'IF Condition',
          name: 'Amount > $10,000?',
          type: 'LOGIC_IF',
          category: 'LOGIC',
          description: 'Routes to VIP channel if amount exceeds threshold',
          status: 'PENDING',
          config: {
            conditionExpression: '$json.amount > 10000',
          },
        },
      },
      {
        id: 'node-slack-5',
        type: 'actionNode',
        position: { x: 1420, y: 100 },
        data: {
          label: 'Slack Notification',
          name: 'Post to #vip-orders',
          type: 'ACTION_SLACK',
          category: 'ACTION',
          description: 'Alerts VIP account executive on Slack',
          status: 'PENDING',
          config: {
            slackChannel: '#vip-sales-alerts',
            slackMessage: '🚨 New VIP Transaction! Order {{ $json.orderId }} for ${{ $json.amount }} from {{ $json.email }} has been verified.',
          },
        },
      },
      {
        id: 'node-email-6',
        type: 'actionNode',
        position: { x: 1420, y: 340 },
        data: {
          label: 'Send Email',
          name: 'Customer Receipt',
          type: 'ACTION_EMAIL',
          category: 'ACTION',
          description: 'Sends standard receipt to buyer',
          status: 'PENDING',
          config: {
            emailTo: '{{ $json.email }}',
            emailSubject: 'Your order confirmation #{{ $json.orderId }}',
            emailBody: 'Thank you for your order of ${{ $json.amount }}. Your payment was processed successfully.',
          },
        },
      },
    ],
    edges: [
      {
        id: 'e-1-2',
        source: 'node-webhook-1',
        target: 'node-transform-2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#06b6d4', strokeWidth: 2 },
      },
      {
        id: 'e-2-3',
        source: 'node-transform-2',
        target: 'node-http-3',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 },
      },
      {
        id: 'e-3-4',
        source: 'node-http-3',
        target: 'node-if-4',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#f59e0b', strokeWidth: 2 },
      },
      {
        id: 'e-4-5-true',
        source: 'node-if-4',
        sourceHandle: 'true',
        target: 'node-slack-5',
        type: 'smoothstep',
        animated: true,
        label: 'TRUE (Amount > 10,000)',
        labelStyle: { fill: '#10b981', fontWeight: 600, fontSize: 11 },
        labelBgStyle: { fill: '#0a1612', fillOpacity: 0.9, stroke: '#10b981', rx: 6 },
        style: { stroke: '#10b981', strokeWidth: 2.5 },
      },
      {
        id: 'e-4-6-false',
        source: 'node-if-4',
        sourceHandle: 'false',
        target: 'node-email-6',
        type: 'smoothstep',
        animated: true,
        label: 'FALSE (Standard)',
        labelStyle: { fill: '#f43f5e', fontWeight: 600, fontSize: 11 },
        labelBgStyle: { fill: '#1f0d14', fillOpacity: 0.9, stroke: '#f43f5e', rx: 6 },
        style: { stroke: '#f43f5e', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'db-sync-workflow',
    name: 'Scheduled Postgres ETL & Slack Alert',
    description: 'Runs on a 15-minute cron schedule, queries PostgreSQL database, and posts summaries',
    category: 'Data & ETL',
    tags: ['Cron', 'PostgreSQL', 'Slack', 'Scheduled'],
    nodes: [
      {
        id: 'node-cron-1',
        type: 'triggerNode',
        position: { x: 100, y: 180 },
        data: {
          label: 'Schedule Trigger',
          name: 'Every 15 Minutes',
          type: 'TRIGGER_SCHEDULE',
          category: 'TRIGGER',
          description: 'Cron scheduler with Redis distributed lock',
          status: 'READY',
          config: {
            cronExpression: '*/15 * * * *',
          },
        },
      },
      {
        id: 'node-pg-2',
        type: 'actionNode',
        position: { x: 440, y: 180 },
        data: {
          label: 'PostgreSQL Query',
          name: 'Find Failed Jobs',
          type: 'ACTION_POSTGRESQL',
          category: 'ACTION',
          description: 'Executes parameterized query against execution_db',
          status: 'PENDING',
          config: {
            sqlQuery: 'SELECT id, workflow_id, error_message FROM execution_logs WHERE status = \'FAILED\' AND created_at > NOW() - INTERVAL \'15 minutes\';',
          },
        },
      },
      {
        id: 'node-slack-3',
        type: 'actionNode',
        position: { x: 780, y: 180 },
        data: {
          label: 'Slack Notification',
          name: 'Post Failed Job Digest',
          type: 'ACTION_SLACK',
          category: 'ACTION',
          description: 'Notifies #oncall-alerts channel with query output',
          status: 'PENDING',
          config: {
            slackChannel: '#oncall-alerts',
            slackMessage: '⚠️ FlowForge Health Alert: Found {{ $json.length }} failed node executions in the last 15 minutes.',
          },
        },
      },
    ],
    edges: [
      {
        id: 'e-cron-pg',
        source: 'node-cron-1',
        target: 'node-pg-2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#06b6d4', strokeWidth: 2 },
      },
      {
        id: 'e-pg-slack',
        source: 'node-pg-2',
        target: 'node-slack-3',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#f59e0b', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'ai-doc-analysis',
    name: 'Multi-Stage LLM Retrieval & Synthesis',
    description: 'Ingests documents via webhook, performs semantic lookup via HTTP, evaluates confidence, and alerts analyst on Slack or stores in DB.',
    category: 'AI & Machine Learning',
    tags: ['Webhook', 'AI / LLM', 'Vector Search', 'Dual Branch'],
    nodes: [
      {
        id: 'node-doc-inbound',
        type: 'triggerNode',
        position: { x: 60, y: 200 },
        data: {
          label: 'Document Webhook',
          name: 'Inbound PDF Ingest',
          type: 'TRIGGER_WEBHOOK',
          category: 'TRIGGER',
          description: 'Listens for document upload event payload',
          status: 'READY',
          config: { webhookPath: '/webhooks/v1/inbound-docs' },
          lastOutput: { docId: 'DOC-88219', title: 'Q4 Enterprise SLA Contract', pages: 18 },
        },
      },
      {
        id: 'node-transform-chunk',
        type: 'dataNode',
        position: { x: 380, y: 200 },
        data: {
          label: 'Transform & Chunk',
          name: 'Text Parser',
          type: 'DATA_TRANSFORM',
          category: 'DATA',
          description: 'Normalizes text, strips headers, calculates token length',
          status: 'PENDING',
          config: { transformCode: 'return { docId: $json.docId, tokens: 4200, status: "CHUNKED" };' },
        },
      },
      {
        id: 'node-llm-call',
        type: 'actionNode',
        position: { x: 700, y: 200 },
        data: {
          label: 'LLM Inference API',
          name: 'Contract Risk Evaluation',
          type: 'ACTION_HTTP',
          category: 'ACTION',
          description: 'POST prompt to OpenAI/Anthropic model endpoint',
          status: 'PENDING',
          config: { method: 'POST', url: 'https://api.openai.com/v1/chat/completions' },
        },
      },
      {
        id: 'node-confidence-check',
        type: 'logicNode',
        position: { x: 1040, y: 190 },
        data: {
          label: 'IF Condition',
          name: 'Confidence >= 90%?',
          type: 'LOGIC_IF',
          category: 'LOGIC',
          description: 'Validates model certainty before automatic approval',
          status: 'PENDING',
          config: { conditionExpression: '$json.confidenceScore >= 0.90' },
        },
      },
      {
        id: 'node-save-pg',
        type: 'actionNode',
        position: { x: 1380, y: 100 },
        data: {
          label: 'PostgreSQL Insert',
          name: 'Auto-Approve Contract',
          type: 'ACTION_POSTGRESQL',
          category: 'ACTION',
          description: 'Inserts vetted document metadata into approved_contracts',
          status: 'PENDING',
          config: { sqlQuery: 'INSERT INTO approved_contracts (doc_id, status) VALUES ($json.docId, "APPROVED");' },
        },
      },
      {
        id: 'node-human-review',
        type: 'actionNode',
        position: { x: 1380, y: 320 },
        data: {
          label: 'Slack Notification',
          name: 'Manual Legal Review',
          type: 'ACTION_SLACK',
          category: 'ACTION',
          description: 'Alerts legal team for manual signoff on ambiguous clause',
          status: 'PENDING',
          config: { slackChannel: '#legal-contracts', slackMessage: '⚠️ Document {{ $json.docId }} requires manual attorney inspection.' },
        },
      },
    ],
    edges: [
      { id: 'e-doc-trans', source: 'node-doc-inbound', target: 'node-transform-chunk', type: 'smoothstep', animated: true, style: { stroke: '#06b6d4', strokeWidth: 2 } },
      { id: 'e-trans-llm', source: 'node-transform-chunk', target: 'node-llm-call', type: 'smoothstep', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-llm-check', source: 'node-llm-call', target: 'node-confidence-check', type: 'smoothstep', animated: true, style: { stroke: '#f59e0b', strokeWidth: 2 } },
      { id: 'e-check-save-true', source: 'node-confidence-check', sourceHandle: 'true', target: 'node-save-pg', type: 'smoothstep', animated: true, label: 'HIGH CONFIDENCE', labelStyle: { fill: '#10b981', fontWeight: 600, fontSize: 11 }, labelBgStyle: { fill: '#0a1612', stroke: '#10b981', rx: 6 }, style: { stroke: '#10b981', strokeWidth: 2.5 } },
      { id: 'e-check-slack-false', source: 'node-confidence-check', sourceHandle: 'false', target: 'node-human-review', type: 'smoothstep', animated: true, label: 'MANUAL REVIEW', labelStyle: { fill: '#f43f5e', fontWeight: 600, fontSize: 11 }, labelBgStyle: { fill: '#1f0d14', stroke: '#f43f5e', rx: 6 }, style: { stroke: '#f43f5e', strokeWidth: 2 } },
    ],
  },
  {
    id: 'kyc-pipeline',
    name: 'Customer Onboarding & KYC Pipeline',
    description: 'Triggered when a new user registers: verifies identity credentials against national databases, logs record to PostgreSQL, and sends tailored email.',
    category: 'Identity & Compliance',
    tags: ['Auth', 'PostgreSQL', 'REST API', 'Transactional Email'],
    nodes: [
      {
        id: 'node-kyc-trigger',
        type: 'triggerNode',
        position: { x: 80, y: 190 },
        data: {
          label: 'Webhook Trigger',
          name: 'Account Signup Event',
          type: 'TRIGGER_WEBHOOK',
          category: 'TRIGGER',
          description: 'Receives user.created event from flowforge-auth',
          status: 'READY',
          config: { webhookPath: '/webhooks/v1/auth-events' },
          lastOutput: { userId: 'usr_77192', email: 'vinit@example.com', country: 'US' },
        },
      },
      {
        id: 'node-kyc-verify',
        type: 'actionNode',
        position: { x: 420, y: 190 },
        data: {
          label: 'HTTP Verification',
          name: 'Passbase / Persona KYC',
          type: 'ACTION_HTTP',
          category: 'ACTION',
          description: 'Submits user profile to KYC identity verification API',
          status: 'PENDING',
          config: { method: 'POST', url: 'https://api.withpersona.com/v1/inquiries' },
        },
      },
      {
        id: 'node-kyc-db',
        type: 'actionNode',
        position: { x: 760, y: 190 },
        data: {
          label: 'PostgreSQL Query',
          name: 'Update User Verification',
          type: 'ACTION_POSTGRESQL',
          category: 'ACTION',
          description: 'Flags verified status in auth_db',
          status: 'PENDING',
          config: { sqlQuery: 'UPDATE users SET kyc_verified = true WHERE id = $json.userId;' },
        },
      },
      {
        id: 'node-kyc-welcome',
        type: 'actionNode',
        position: { x: 1100, y: 190 },
        data: {
          label: 'Send Email',
          name: 'Dispatch Welcome Kit',
          type: 'ACTION_EMAIL',
          category: 'ACTION',
          description: 'Sends onboarding instructions to the newly validated user',
          status: 'PENDING',
          config: { emailTo: '{{ $json.email }}', emailSubject: 'Welcome to FlowForge Enterprise' },
        },
      },
    ],
    edges: [
      { id: 'e-kyc-1-2', source: 'node-kyc-trigger', target: 'node-kyc-verify', type: 'smoothstep', animated: true, style: { stroke: '#06b6d4', strokeWidth: 2 } },
      { id: 'e-kyc-2-3', source: 'node-kyc-verify', target: 'node-kyc-db', type: 'smoothstep', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-kyc-3-4', source: 'node-kyc-db', target: 'node-kyc-welcome', type: 'smoothstep', animated: true, style: { stroke: '#8b5cf6', strokeWidth: 2 } },
    ],
  },
];
